OT2023/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from profesorado import views as profesorado_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', profesorado_views.dashboard),
    path('live/', profesorado_views.live),
    path('profesorado/', include('profesorado.urls', namespace='profesorado')),
    path('jurado/', include('jurado.urls', namespace='jurado')),
    path('alumnado/', include('alumnado.urls', namespace='alumnado')),
    # path('search/<str:search_str>/', profesorado_views.search, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alumnado/urls.py
from django.urls import path

from . import views

app_name = 'alumnado'

urlpatterns = [
    path('', views.alumnado_list, name='alumnado_list'),
    path('<slug:alumnado_slug>/', views.alumnado_detail, name='alumnado_detail'),
]

jurado/urls.py
from django.urls import path

from . import views

app_name = 'jurado'

urlpatterns = [
    path('', views.jurado_list, name='jurado_list'),
    path('<slug:jurado_slug>/', views.jurado_detail, name='jurado_detail'),
]

profesorado/urls.py
from django.urls import path

from . import views

app_name = 'profesorado'

urlpatterns = [
    path('', views.profesorado_list, name='profesorado_list'),
    path('<slug:profe_slug>/', views.profesorado_detail, name='profesorado_detail'),
]

alumnado/models.py
from django.db import models


class MusicStyle(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)

    def __str__(self):
        return self.name


class Alumnado(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    birthday = models.CharField(max_length=200)
    is_from = models.CharField(max_length=250)
    job = models.CharField(max_length=250)
    hobbies = models.CharField(max_length=250)
    avatar = models.ImageField(upload_to='media/%Y/%m/%d', blank=True)
    eliminated = models.BooleanField(null=True)
    music_style = models.ManyToManyField(MusicStyle)

    def __str__(self):
        return self.name

jurado/models.py
from django.db import models


class Jurado(models.Model):
    name = models.CharField(max_length=250)
    age = models.IntegerField()
    slug = models.SlugField(max_length=250)
    description = models.TextField(blank=True)
    is_from = models.CharField(max_length=250)
    avatar = models.ImageField(upload_to='media/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.name

profesorado/models.py
from django.db import models


class Profesorado(models.Model):
    name = models.CharField(max_length=200, default='')
    slug = models.SlugField(max_length=250, default='')
    image = models.ImageField(upload_to='media/%Y/%m/%d', blank=True)
    origen = models.TextField(blank=True)
    edad = models.IntegerField()
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

alumnado/views.py
from django.shortcuts import get_object_or_404, render

from .models import Alumnado


def alumnado_list(request):
    alumnados = Alumnado.objects.all()
    return render(request, 'alumnados/list.html', {'alumnados': alumnados})


def alumnado_detail(request, alumnado_slug: str):
    alumnado = get_object_or_404(Alumnado, slug=alumnado_slug)
    music_style = alumnado.music_style.all()
    return render(
        request, 'alumnados/detail.html', {'alumnado': alumnado, 'music_style': music_style}
    )

jurado/views.py
from django.shortcuts import get_object_or_404, render

from .models import Jurado


def jurado_list(request):
    jurados = Jurado.objects.all()
    return render(request, 'jurados/list.html', {'jurados': jurados})


def jurado_detail(request, jurado_slug: str):
    jurado = get_object_or_404(Jurado, slug=jurado_slug)
    return render(request, 'jurados/detail.html', {'jurado': jurado})

profesorado/views.py
from django.shortcuts import get_object_or_404, render
from django.apps import apps

from .models import Profesorado


def dashboard(request):
    return render(request, 'dashboard.html', {'section': 'dashboard'})


def live(request):
    return render(request, 'live.html', {'section': 'live'})


def profesorado_list(request):
    profes = Profesorado.objects.all()
    return render(request, 'profes/list.html', {'profes': profes})


def profesorado_detail(request, profe_slug: str):
    profe = get_object_or_404(Profesorado, slug=profe_slug)
    return render(request, 'profes/detail.html', {'profe': profe})


# def search(request, search_str:str = None):
#     resultados  = {}
    
#     # Obtener todos los modelos registrados en la aplicación Django
#     modelos = apps.get_models()

#     # Iterar sobre los modelos y realizar una consulta para cada uno
#     for modelo in modelos:
#         # Obtener el nombre de la tabla asociada al modelo
#         nombre_tabla = modelo._meta.db_table

#         # Realizar la consulta utilizando el método filter
#         datos_tabla = modelo.objects.filter(search_str__icontains=search_str)

#         # Almacenar los res en un diccionario
#         resultados[nombre_tabla] = list(datos_tabla.values())
#     return render(request, 'search.html', {'search': resultados})

alumnado/templates/alumnados/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div id="data">
    <div id="imgProfe">
      <img src="{% if alumnado.avatar %}
          {{ alumnado.avatar.url }}
        {% else %}
          {% static 'img/no_image.jpg' %}
        {% endif %}" />
      <h2 class="card-title">{{ alumnado.name }}</h2>
    </div>
    <div id="dataProfe">
      <div>
        <i class="bi bi-geo-fill" style="font-size: 30px;"></i>
        <h5>{{ alumnado.is_from }}</h5>
      </div>
      <div>
        <i class="bi bi-person-fill" style="font-size: 30px;"></i>
        <h5>{{ alumnado.birthday }}</h5>
      </div>
      <div>
        <i class="bi bi-info-circle-fill" style="font-size: 30px;"></i>
        <p>{{ alumnado.job }}</p>
      </div>
      <div>
        <i class="bi bi-hourglass-split" style="font-size: 30px;"></i>
        <p>{{ alumnado.hobbies }}</p>
      </div>
      <div>
        <i class="bi bi-music-note-list" style="font-size: 30px;"></i>
          <p>{{ music_style|join:', ' }}</p>
      </div>
    </div>
  </div>
{% endblock %}

alumnado/templates/alumnados/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Alumnado
{% endblock %}
{% block content %}
  <div class="container text-center" id="alumnadoContent">
    <div class="row justify-content-center align-content-center">
      {% for alumnado in alumnados %}
        <div class="col-2 justify-content-center" style="display: flex;">
          <a href="{% url 'alumnado:alumnado_detail' alumnado.slug %}">
            <div class="card" id="personCard">
              {% if alumnado.eliminated %}
                <img id="imgCard"
                  src="{% if alumnado.avatar %}
                  {% comment %} Falta añadir filtro para alumnado eliminado {% endcomment %}
                    {{ alumnado.avatar.url }}
                  {% else %}
                    {% static 'img/no_image.jpg' %}
                  {% endif %}"
                  class="card-img-top"
                  style="filter: grayscale(100%);" />
              {% else %}
                <img id="imgCard"
                src="{% if alumnado.avatar %}
                {% comment %} Falta añadir filtro para alumnado eliminado {% endcomment %}
                  {{ alumnado.avatar.url }}
                {% else %}
                  {% static 'img/no_image.jpg' %}
                {% endif %}"
                class="card-img-top"
                style="filter: grayscale(0%);" />
              {% endif %}  
              <div class="card-body">
                <p class="card-title">{{ alumnado.name }}</p>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

jurado/templates/jurados/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Jurado
{% endblock %}
{% block content %}
  <div class="container text-center" id="juradoContent">
    <div class="row justify-content-center align-content-center">
      {% for jurado in jurados %}
        <div class="col-2 justify-content-center" style="display: flex;">
          <a href="{% url 'jurado:jurado_detail' jurado.slug %}">
            <div class="card" id="personCard">
              <img id="imgCard"
                src="{% if jurado.avatar %}
                  {{ jurado.avatar.url }}
                {% else %}
                  {% static 'img/no_image.jpg' %}
                {% endif %}"
                class="card-img-top" />
              <div class="card-body">
                <p class="card-title">{{ jurado.name }}</p>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

profesorado/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>
      {% block title %}
        OT2023
      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" /> <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/"><img class="logoImg" src="{% static 'img/logo.png' %}" ></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'profesorado:profesorado_list' %}">Profesorado</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'alumnado:alumnado_list' %}">Alumnado</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'jurado:jurado_list' %}">Jurado</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="http://127.0.0.1:8000/live/">Live 24h</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
            <button class="btn btn-outline-primary" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="content">
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>

profesorado/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Dashboard
{% endblock %}
{% block content %}
  <div id="dashboardContent">
    <h1 class="title">OPERACIÓN TRIUNFO 2023</h1>
    <div class="container justify-content-center" style="display: flex;">
      <div class="row align-items-center" id="dashCards">
        <div class="col-4">
          <a href="{% url 'profesorado:profesorado_list' %}">
            <div class="card text-bg-dark" id="contentCard" style="width: 100%;">
              <img src="{% static 'img/profes.png' %}" class="card-img" />
              <div class="card-img-overlay" id="cardOverlay">
                <h5 class="card-title" id="cardTitle">Profesorado</h5>
              </div>
            </div>
          </a>
        </div>
        <div class="col-4">
          <a href="{% url 'alumnado:alumnado_list' %}">
            <div class="card text-bg-dark" id="contentCard" style="width: 100%;">
              <img src="{% static 'img/alumnado.png' %}" class="card-img" alt="..." />
              <div class="card-img-overlay" id="cardOverlay">
                <h5 id="cardTitle">Alumnado</h5>
              </div>
            </div>
          </a>
        </div>
        <div class="col-4">
          <a href="{% url 'jurado:jurado_list' %}">
            <div class="card text-bg-dark" id="contentCard" style="width: 100%;">
              <img src="{% static 'img/jurado.png' %}" class="card-img" alt="..." />
              <div class="card-img-overlay" id="cardOverlay">
                <h5 class="card-title" id="cardTitle">Jurado</h5>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

profesorado/templates/live.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Live
{% endblock %}
{% block content %}
    <iframe src="https://www.spatial.io/s/Operacion-Triunfo-2023-6575b4cb59d29d0853dcf209?share=5861431769820707293" frameborder="0"></iframe>
{% endblock %}

profesorado/templates/profes/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div id="data">
    <div id="imgProfe">
      <img src="{% if profe.image %}
          {{ profe.image.url }}
        {% else %}
          {% static 'img/no_image.jpg' %}
        {% endif %}"
        alt="" />
      <h2 class="card-title">{{ profe.name }}</h2>
    </div>
    <div id="dataProfe">
      <div>
        <i class="bi bi-geo-fill" style="font-size: 30px;"></i>
        <h5>{{ profe.origen }}</h5>
      </div>
      <div>
        <i class="bi bi-person-fill" style="font-size: 30px;"></i>
        <h5>{{ profe.edad }} años</h5>
      </div>
      <div>
        <i class="bi bi-info-circle-fill" style="font-size: 30px;"></i>
        <h5>{{ profe.description }}</h5>
      </div>
    </div>
  </div>
{% endblock %}

profesorado/templates/profes/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Profesorado
{% endblock %}
{% block content %}
  <div class="container text-center" id="profesoradoContent">
    <div class="row justify-content-center align-content-center">
      {% for profe in profes %}
        <div class="col-2 justify-content-center" style="display: flex;">
          <a href="{% url 'profesorado:profesorado_detail' profe.slug %}">
            <div class="card" id="personCard">
              <img id="imgCard"
                src="{% if profe.image %}
                  {{ profe.image.url }}
                {% else %}
                  {% static 'img/no_image.jpg' %}
                {% endif %}"
                class="card-img-top" />
              <div class="card-body">
                <p class="card-title">{{ profe.name }}</p>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

profesorado/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% for resultado in resultados %}
        <div>
            <p>{{resultado.name}}</p>
        </div>
{% endblock %}